// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyJ7fPMDjorCJqIhhp4RiakHxdbuO2ZIY',
    appId: '1:743497287904:web:b41f88fd89e216fc412885',
    messagingSenderId: '743497287904',
    projectId: 'flutter-firebase-templat-9af89',
    authDomain: 'flutter-firebase-templat-9af89.firebaseapp.com',
    storageBucket: 'flutter-firebase-templat-9af89.appspot.com',
    measurementId: 'G-Y8K6K8B59Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKJNHsfMe2uIbOxt9sLhfg9dq23v91SJE',
    appId: '1:743497287904:android:f05181b87838c5c3412885',
    messagingSenderId: '743497287904',
    projectId: 'flutter-firebase-templat-9af89',
    storageBucket: 'flutter-firebase-templat-9af89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkTlu7bV-mokqMYAPUY6XbA3i8Oak3vTM',
    appId: '1:743497287904:ios:816e80e4a2004f2d412885',
    messagingSenderId: '743497287904',
    projectId: 'flutter-firebase-templat-9af89',
    storageBucket: 'flutter-firebase-templat-9af89.appspot.com',
    iosClientId: '743497287904-5jn5tilqlqmr9kjj5hd5mjsh4fnstlkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkTlu7bV-mokqMYAPUY6XbA3i8Oak3vTM',
    appId: '1:743497287904:ios:816e80e4a2004f2d412885',
    messagingSenderId: '743497287904',
    projectId: 'flutter-firebase-templat-9af89',
    storageBucket: 'flutter-firebase-templat-9af89.appspot.com',
    iosClientId: '743497287904-5jn5tilqlqmr9kjj5hd5mjsh4fnstlkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseTemplate',
  );
}
